version: "1.0"
services:
     pre-pro-bot:
      container_name: nl-bot
      image: nl-bot
      restart: unless-stopped  
      environment:
        - DATABASE_URL=TOKEN_HERE
        - DISCORD_TOKEN=TOKEN_HERE
      ports:
        - "3000:3000"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
